import OpenAI from 'openai'

export const runtime = 'edge'

const PROMPT_SYSTEM = `You are a world-class creative director and art director at a Madison Avenue advertising agency. 
You write image generation prompts that produce editorial, photorealistic, high-end photography.

Given a product brief, you write 5 distinct image prompts — each for a specific use case.
Every prompt must feel like it was art directed by a human creative director, not generated by AI.

Rules:
- Always specify lighting (golden hour, soft window light, studio rim light, etc.)
- Always specify camera/lens feel (85mm f/1.4 portrait, 35mm street, wide architectural, etc.)
- Always specify mood and color temperature
- Reference real photography styles (editorial, documentary, architectural, still life, etc.)
- Never use generic descriptions — be specific about the scene, the subject, the moment
- The output must look NOTHING like stock photography
- Avoid AI tells: no perfect symmetry, no overly clean scenes, real texture and imperfection
- Each prompt must end with: "Shot for a luxury brand campaign. Not stock photography. Real, human, specific."

Output ONLY valid JSON in this exact format, no other text:
{
  "prompts": [
    {
      "use": "hero",
      "label": "Website Hero / Presentation Cover",
      "prompt": "..."
    },
    {
      "use": "feature", 
      "label": "Product/Service in Action",
      "prompt": "..."
    },
    {
      "use": "human",
      "label": "The Human Element / Testimonial",
      "prompt": "..."
    },
    {
      "use": "atmosphere",
      "label": "Atmospheric / Brand Mood",
      "prompt": "..."
    },
    {
      "use": "social",
      "label": "Social Media / Square Crop",
      "prompt": "..."
    }
  ],
  "unsplashQueries": [
    "query1 for hero image",
    "query2 for feature image", 
    "query3 for human element",
    "query4 for atmosphere",
    "query5 for social"
  ]
}`

export async function POST(req: Request) {
  const openai = new OpenAI({
    apiKey: process.env.OPENROUTER_API_KEY,
    baseURL: 'https://openrouter.ai/api/v1',
  })
  try {
    const { brief, productName, industry, tagline } = await req.json()

    const userMessage = `
Product: ${productName}
Industry: ${industry || 'Business/Technology'}
Tagline: ${tagline || ''}

Brief excerpt:
${brief?.slice(0, 1500) || ''}

Write 5 image prompts for this product following the Madison Avenue creative direction standard.
Make each prompt specific to this exact product and industry — not generic.
`

    const response = await openai.chat.completions.create({
      model: 'google/gemini-2.5-flash',
      max_tokens: 2000,
      messages: [
        { role: 'system', content: PROMPT_SYSTEM },
        { role: 'user', content: userMessage }
      ]
    })

    const text = response.choices[0]?.message?.content || ''
    
    // Strip markdown fences if present
    const clean = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    
    try {
      const data = JSON.parse(clean)
      return Response.json(data)
    } catch {
      return Response.json({ error: 'Failed to parse prompts', raw: text }, { status: 500 })
    }
  } catch (err: any) {
    return Response.json({ error: err.message }, { status: 500 })
  }
}
